### ISSUE TITLE
RMiner freezes on commit

### ISSUE THREAD

**Issue by RamSaw** [ml-in-programming/RefactoringDataSet#4]
When we run RMiner on [Xerces2-j](https://github.com/apache/xerces2-j.git) project it freezes on commit 6496e08b112a154379c9904c2f9a0a0d9941fbe5. This commit is 4054 / 5507.
apache/xerces2-j@6496e08

**Comment by Ivan-Veselov** [comment]
Works fine if it's run on this commit only. RMiner finds no refactorings.

**Comment by Ivan-Veselov** [comment]
Also want to notice that there are no modified java files in this commit.

**Comment by Ivan-Veselov** [comment]
It seems like the problem is in the next commit: https://github.com/apache/xerces2-j/commit/6fec9ee0c874aba003c6652a39c4de16036f6e4f. It's very huge, and it took about 20 minutes on my machine to process it. But it finished.
